/** Interoperability Incident Room backend. Paste this entire file into the
 * Apps Script project bound to the same Sheet as Kano, then deploy a new
 * version. Kano actions continue to be handled by the original Code.gs.
 * If combining files, rename Kano's doGet/doPost to kanoDoGet/kanoDoPost,
 * rename this file's doGet/doPost to the public names, and use the fallback
 * calls below. A simpler, safer option is a separate Apps Script deployment. */
const INTEROP_PIN='harigopalan';
const INTEROP_STUDENTS='Interop_Students',INTEROP_ATTEMPTS='Interop_Attempts',INTEROP_RESULTS='Interop_Results',INTEROP_PROGRESS='Interop_Progress';
const IH={students:['studentId','displayName','username','pin','scenarioId','enabled'],attempts:['timestamp','studentId','studentName','scenarioId','questionId','competencyId','attemptNumber','selectedOption','correct','questionCompleted','pointsEarnedWhenCompleted'],results:['completedAt','studentId','displayName','scenarioId','weightedRawScore','transmutedGrade','passed','firstAttemptCount','secondAttemptCount','thirdAttemptCount','missedCount'],progress:['studentId','updatedAt','dataJSON']};
function iSheet_(name,headers){const ss=SpreadsheetApp.getActiveSpreadsheet();let s=ss.getSheetByName(name);if(!s){s=ss.insertSheet(name);s.appendRow(headers)}return s}
function iOut_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function iRows_(s){const v=s.getDataRange().getValues();return v.slice(1).filter(r=>r[0]!==''&&r[0]!=null)}
function iBool_(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}
function iFind_(s,col,value){const rows=s.getDataRange().getValues();const t=String(value).trim().toLowerCase();for(let i=1;i<rows.length;i++)if(String(rows[i][col]).trim().toLowerCase()===t)return i+1;return-1}
function iProgress_(studentId){const s=iSheet_(INTEROP_PROGRESS,IH.progress),r=iFind_(s,0,studentId);if(r<0)return null;try{return JSON.parse(s.getRange(r,3).getValue()||'null')}catch(e){return null}}
function iSaveProgress_(p){const s=iSheet_(INTEROP_PROGRESS,IH.progress),id=p.student.studentId,r=iFind_(s,0,id),row=[id,new Date().toISOString(),JSON.stringify(p)];if(r<0)s.appendRow(row);else s.getRange(r,1,1,row.length).setValues([row])}
function iInstructor_(b){if(String(b.pin)!==INTEROP_PIN)throw Error('bad_pin')}
function iSetup_(){const s=iSheet_(INTEROP_STUDENTS,IH.students);s.getRange(1,1,1,IH.students.length).setValues([IH.students]);iSheet_(INTEROP_ATTEMPTS,IH.attempts);iSheet_(INTEROP_RESULTS,IH.results);iSheet_(INTEROP_PROGRESS,IH.progress)}
function setupInteroperability(){iSetup_();return 'Interop sheets are ready.'}
function doGet(e){const p=e&&e.parameter?e.parameter:{};if(!p.app||p.app==='interoperability'){iSetup_();return iOut_({ok:true,app:'interoperability',status:'ready',sheetsReady:true,message:'Interoperability Incident Room backend is ready.'})}if(typeof kanoDoGet==='function')return kanoDoGet(e);return iOut_({ok:false,error:'unknown_app'})}
function doPost(e){let b;try{b=JSON.parse(e.postData.contents)}catch(err){return iOut_({ok:false,error:'bad_request'})}if(b.app!=='interoperability'){if(typeof kanoDoPost==='function')return kanoDoPost(e);return iOut_({ok:false,error:'unknown_app'})}try{return iOut_(iAction_(b))}catch(err){return iOut_({ok:false,error:String(err.message||err)})}}
function iAction_(b){const students=iSheet_(INTEROP_STUDENTS,IH.students),attempts=iSheet_(INTEROP_ATTEMPTS,IH.attempts),results=iSheet_(INTEROP_RESULTS,IH.results);
 if(b.action==='studentLogin'){const rows=iRows_(students),name=String(b.studentName||'').trim(),target=name.toLowerCase(),pin=String(b.pin||'').trim();if(name.length<2)throw Error('Enter your full student name.');if(pin.length<4)throw Error('PIN must contain at least 4 characters.');let row=rows.find(r=>String(r[1]).trim().toLowerCase()===target);let created=false;if(!row){const counts={A:0,B:0,C:0,D:0,E:0};rows.forEach(r=>{const id=String(r[4]);if(counts[id]!==undefined)counts[id]++});const assigned=Object.keys(counts).sort((a,b)=>counts[a]-counts[b]||a.localeCompare(b))[0];const studentId='STU-'+Utilities.getUuid().slice(0,8).toUpperCase();row=[studentId,name,'',pin,assigned,true];students.appendRow(row);created=true}if(String(row[3])!==pin)throw Error('Incorrect PIN for this student name.');if(!iBool_(row[5]))throw Error('This student record is disabled.');if(!/^[A-E]$/.test(String(row[4])))throw Error('Scenario assignment must be A, B, C, D or E.');const student={studentId:String(row[0]),displayName:String(row[1]),username:'',scenarioId:String(row[4]),enabled:true};return{ok:true,student:student,progress:iProgress_(student.studentId),newStudent:created}}
 if(b.action==='saveAttempt'){const a=b.attempt,p=b.progress;if(!a||!p)throw Error('missing_data');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const prior=iRows_(attempts).some(r=>String(r[1])===String(a.studentId)&&String(r[4])===String(a.questionId)&&Number(r[6])===Number(a.attemptNumber));if(prior)throw Error('duplicate_attempt');attempts.appendRow([a.timestamp,a.studentId,a.studentName,a.scenarioId,a.questionId,a.competencyId,a.attemptNumber,a.selectedOption,a.correct,a.questionCompleted,a.pointsEarnedWhenCompleted]);iSaveProgress_(p)}finally{lock.releaseLock()}return{ok:true}}
 if(b.action==='saveResult'){const r=b.result,p=b.progress;if(!r||!p)throw Error('missing_data');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const existing=iFind_(results,1,r.studentId);if(existing<0)results.appendRow([r.completedAt,r.studentId,r.displayName,r.scenarioId,r.weightedRawScore,r.transmutedGrade,r.passed,r.firstAttemptCount,r.secondAttemptCount,r.thirdAttemptCount,r.missedCount]);iSaveProgress_(p)}finally{lock.releaseLock()}return{ok:true}}
 if(b.action==='instructorData'){iInstructor_(b);const ss=iRows_(students).map(r=>({studentId:String(r[0]),displayName:String(r[1]),username:String(r[2]),scenarioId:String(r[4]),enabled:iBool_(r[5])}));const aa=iRows_(attempts).map(r=>({timestamp:String(r[0]),studentId:String(r[1]),studentName:String(r[2]),scenarioId:String(r[3]),questionId:String(r[4]),competencyId:String(r[5]),attemptNumber:Number(r[6]),selectedOption:String(r[7]),correct:iBool_(r[8]),questionCompleted:iBool_(r[9]),pointsEarnedWhenCompleted:Number(r[10])}));const rr=iRows_(results).map(r=>({completedAt:String(r[0]),studentId:String(r[1]),displayName:String(r[2]),scenarioId:String(r[3]),weightedRawScore:Number(r[4]),transmutedGrade:Number(r[5]),passed:iBool_(r[6]),firstAttemptCount:Number(r[7]),secondAttemptCount:Number(r[8]),thirdAttemptCount:Number(r[9]),missedCount:Number(r[10])}));const pp=iRows_(iSheet_(INTEROP_PROGRESS,IH.progress)).map(r=>{try{return JSON.parse(r[2])}catch(e){return null}}).filter(Boolean);return{ok:true,students:ss,attempts:aa,results:rr,progress:pp}}
 if(b.action==='resetStudent'){iInstructor_(b);const id=String(b.studentId),lock=LockService.getScriptLock();lock.waitLock(10000);try{[attempts,results,iSheet_(INTEROP_PROGRESS,IH.progress)].forEach((s,idx)=>{const col=idx===0?1:idx===1?1:0;for(let r=s.getLastRow();r>=2;r--)if(String(s.getRange(r,col+1).getValue())===id)s.deleteRow(r)})}finally{lock.releaseLock()}return{ok:true}}
 throw Error('unknown_action')}
